{
 "title": "POD Resources Stat",
 "description": "Get the Pod memory, CPU stats like avg, max usage across a time interval. Particularly helpful for setting and monitoring requests and limits of resources.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "container", "query": { "query": "label_values(container)" } }
  ]
 },
 "panels": [
  {
   "title": "Max Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    sum by (pod) (\n      container_memory_working_set_bytes{\n        namespace=\"$namespace\",\n        container!=\"POD\",\n        container=\"$container\"\n      }\n    )[$__range:]\n  )\n)\n",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(kube_pod_container_status_restarts_total{container=\"$container\", namespace=\"$namespace\"}[1h]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}[1m])))*1000\n",
     "legendFormat": "cpu (cores)"
    }
   ]
  },
  {
   "title": "Avg Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"$namespace\",\r\n    container=\"$container\"\r\n  }\r\n)\r\n",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Avg Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"$namespace\",\n    container=\"$container\"\n  }[1m])\n)\n",
     "legendFormat": "cpu (cores)"
    }
   ]
  }
 ]
}