{
 "title": "prometheus  Server Multiselect",
 "description": "Dashboard to view multiple servers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode=\"system\"})"
    }
   ]
  },
  {
   "title": "CPU Uses",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~'$node'}[5m])) * 100)",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\"}) by (cpu)) * 100",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~'$node'} * 100) / node_memory_MemTotal_bytes{instance=~'$node'})"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[5m])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "repeat": "node",
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "repeat": "node",
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "established"
    }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "repeat": "node",
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_NoPorts"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "repeat": "node",
   "targets": [
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$node\"} - node_nf_conntrack_entries{instance=~\"$node\"}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}